import type { Metadata } from "next";
import { Container } from "./component/Container";


export const metadata: Metadata = {
  title: "スキーマノート",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Container>
          {children}
        </Container>
        </body>
    </html>
  );
}
